
project_id = "sgmntgiiluqrbxkskyhy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.coinbase]
verify_jwt = false

[functions.coinbase-webhook]
verify_jwt = false

[functions.setup-storage]
verify_jwt = false
