
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgmntgiiluqrbxkskyhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnbW50Z2lpbHVxcmJ4a3NreWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTU0NDUsImV4cCI6MjA2MTE5MTQ0NX0.85lJqu3w8fcKjQMMsqkE-YabABwRw786XsN_QAWtvjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
